# requires extention: REST Client for Visual Studio Code

###
GET http://localhost:8000/api/products/16 HTTP/1.1

###
PUT http://localhost:8000/api/products/16 HTTP/1.1
Content-Type: application/json

{
  "name": "Super Secret Product",
  "description": "you're gonna love it",
  "price": "999.00",
  "stock": 3
}

###
DELETE http://localhost:8000/api/products/16 HTTP/1.1

###
POST http://localhost:8000/api/products/ HTTP/1.1
Content-Type: application/json

{
    "name": "Lenovo Laptop Yoga",
    "price": "800",
    "stock": 10,
    "description": "buy at your own risk!"
}
