# ./backend/Dockerfile

FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY requirements*.txt /tmp/
RUN pip install --upgrade pip && pip install -r /tmp/requirements.txt

COPY . .

# No USER directive — in dev, we'll control this from docker-compose
# In prod, we can add USER django-user or similar

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
